spring:
  application:
    name: technical-test
  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USERNAME}
    password: ${SPRING_FLYWAY_PASSWORD}
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

server:
  port: ${SERVER_PORT}